CREATE TABLE orders.Category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

INSERT INTO orders.Category (name, description)
VALUES ('Hambúrgueres', 'Deliciosos hambúrgueres feitos com proteínas suculenta e ingredientes frescos'),
       ('Batatas Fritas', 'Batatas fritas crocantes e saborosas'),
       ('Refrigerantes', 'Uma variedade de refrigerantes gelados'),
       ('Sobremesas', 'Sobremesas doces e deliciosas, perfeitas para finalizar sua refeição'),
       ('Saladas', 'Saladas frescas e saudáveis para uma opção mais leve'),
       ('Sanduíches', 'Sanduíches variados, perfeitos para uma refeição rápida'),
       ('Café da Manhã', 'Opções de café da manhã deliciosas para começar bem o dia');