CREATE TABLE orders.Product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION,
    quantity    INTEGER,
    category_id BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE orders.Product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES orders.Category (id);

-- Inserir produtos para uma rede de fast food

-- Produtos de Hambúrgueres
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Hambúrguer Simples', 'Hambúrguer simples com carne, alface e queijo', 5.99, 100, 1),
       ('Hambúrguer Duplo', 'Hambúrguer duplo com carne, alface, queijo e bacon', 7.99, 80, 1),
       ('Hambúrguer Vegetariano', 'Hambúrguer vegetariano com patty de legumes e queijo', 6.49, 50, 1);

-- Produtos de Batatas Fritas
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Batata Frita Pequena', 'Porção pequena de batatas fritas crocantes', 2.99, 150, 2),
       ('Batata Frita Média', 'Porção média de batatas fritas crocantes', 3.99, 120, 2),
       ('Batata Frita Grande', 'Porção grande de batatas fritas crocantes', 4.99, 100, 2);

-- Produtos de Refrigerantes
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Refrigerante Coca-Cola', 'Lata de 350ml de Coca-Cola gelada', 2.49, 200, 3),
       ('Refrigerante Pepsi', 'Lata de 350ml de Pepsi gelada', 2.49, 180, 3),
       ('Refrigerante Sprite', 'Lata de 350ml de Sprite gelada', 2.49, 170, 3);

-- Produtos de Sobremesas
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Sundae de Chocolate', 'Sundae de chocolate com calda e chantilly', 4.99, 80, 4),
       ('Casquinha de Baunilha', 'Casquinha de sorvete de baunilha crocante', 1.99, 100, 4),
       ('Torta de Maçã', 'Fatia de torta de maçã quente com sorvete de baunilha', 3.99, 60, 4);

-- Produtos de Saladas
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Salada Caesar', 'Salada Caesar com alface, croutons, parmesão e molho Caesar', 5.49, 40, 5),
       ('Salada de Frango Grelhado', 'Salada mista com peito de frango grelhado', 6.49, 30, 5),
       ('Salada de Atum', 'Salada mista com atum em lata', 5.99, 35, 5);

-- Produtos de Sanduíches
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Sanduíche de Frango', 'Sanduíche de frango grelhado com alface e maionese', 4.99, 70, 6),
       ('Sanduíche de Peito de Peru', 'Sanduíche de peito de peru com queijo e alface', 5.49, 60, 6),
       ('Sanduíche Vegano', 'Sanduíche vegano com patty de grãos e vegetais', 5.99, 50, 6);

-- Produtos de Café da Manhã
INSERT INTO orders.Product (name, description, price, quantity, category_id)
VALUES ('Muffin de Ovos e Queijo', 'Muffin inglês com ovo mexido e queijo', 3.49, 60, 7),
       ('Café Preto', 'Café preto quente em copo médio', 1.99, 100, 7),
       ('Combo Café da Manhã', 'Combo com muffin de ovos e queijo e café preto', 4.99, 50, 7);
