CREATE TABLE order_items
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT,
    price      DOUBLE PRECISION,
    quantity   INTEGER
);

CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customerId      BIGINT,
    correlationalId UUID,
    total           DOUBLE PRECISION,
    status          VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE order_items
    ADD CONSTRAINT uc_order_items_product UNIQUE (product_id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_on_order FOREIGN KEY (order_id) REFERENCES orders (id);